[build]
target = "avr-specs/avr-atmega2560.json"
rustflags = ["--cfg", "portable_atomic_unsafe_assume_single_core"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 57600"

[unstable]
build-std = ["core"]
